CED/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('auth/', include('django.contrib.auth.urls'), name='auth'),
    path('', include('Dashboard.urls'), name='dashboard'),
    path('doctorants/', include('Etudiant.urls'), name='doctorant'),
    path('administration/', include('Administration.urls'), name='administration'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Dashboard/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='welcome'),
    path('dashboard/', views.dashboard, name='dashboard'),
]

Administration/models.py
from django.db import models
from django.apps import apps
from phonenumber_field.modelfields import PhoneNumberField
from django.core.validators import MaxValueValidator, MinValueValidator
from CED_Tools.tools.Classes import TimeStampedModel
from CED_Tools.models import Annee, Pays


class Departement(TimeStampedModel):
    class Meta:
        db_table = 'ced_departements'

    intitule = models.CharField(max_length=255)
    description = models.CharField(max_length=255)

    def __str__(self):
        return self.intitule

class Etablissement(TimeStampedModel):
    class Meta:
        db_table = 'ced_etablissements'

    acronyme = models.CharField(max_length=63)
    intitule = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    ville = models.CharField(max_length=255)
    pays = models.ForeignKey(Pays, on_delete=models.DO_NOTHING, related_name='etablissements')
    
    def __str__(self):
        return f"({self.acronyme}) {self.intitule}"

class Enseignant(TimeStampedModel):
    class Meta:
        db_table = 'ced_enseignants'

    nom = models.CharField(max_length=50)
    prenom = models.CharField(max_length=50, blank=True, null=True)
    cin = models.CharField(max_length=50, blank=True, null=True)
    som =  models.CharField(max_length=50, blank=True, null=True)
    grade =  models.CharField(max_length=50, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    telephone = PhoneNumberField(blank=True, null=True)
    etablissement = models.ForeignKey(Etablissement, on_delete=models.DO_NOTHING, related_name='enseignants', blank=True, null=True)
    laboratoire = models.ForeignKey('Laboratoire', on_delete=models.DO_NOTHING, related_name='enseignants', blank=True, null=True)

    def __str__(self):
        return f"{self.nom} {self.prenom or '--'}"

    def get_current_laboratoire(self):
        try:
            return self.laboratoires.filter(courant=True).first().laboratoire
        except:
            return None

    @property
    def current_doctorants(self):
        return apps.get_model('Etudiant','Doctorant').objects.filter(inscriptions__sujet__directeur=self).distinct().filter(soutenances=None)

class FormationDoctorale(TimeStampedModel):
    class Meta:
        db_table = 'ced_formations_doctorales'
    intitule = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    acronyme = models.CharField(max_length=255)
    co_ordonateur = models.ForeignKey(Enseignant, on_delete=models.DO_NOTHING, related_name="formations_doctorales", null=True, blank=True)

    def __str__(self) -> str:
        return f"({self.acronyme}) {self.intitule}"

class Laboratoire(TimeStampedModel):
    class Meta:
        db_table = 'ced_laboratoires'

    intitule = models.CharField(max_length=255)
    acronyme = models.CharField(max_length=255)
    departement = models.ForeignKey(Departement, on_delete=models.DO_NOTHING, related_name="laboratoires")
    formation_doctorale = models.ForeignKey(FormationDoctorale, on_delete=models.DO_NOTHING, related_name="laboratoires")

    def __str__(self):
        return f'({self.acronyme}) -- {self.get_current_directeur() or "--"}'

    def get_current_directeur(self):
        try:
            return self.directeurs.filter(courant=True).first().directeur
        except:
            return None

class LaboratoireDirecteur(TimeStampedModel):
    class Meta:
        db_table = 'ced_laboratoire_directeur'
    directeur = models.ForeignKey(Enseignant, on_delete=models.DO_NOTHING, related_name='laboratoires')
    laboratoire = models.ForeignKey(Laboratoire, on_delete=models.DO_NOTHING, related_name='directeurs')
    courant = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.laboratoire} - {self.directeur}"

class Sujet(TimeStampedModel):

    class Meta:
        db_table = 'ced_sujets'

    annee = models.ForeignKey(Annee, on_delete=models.DO_NOTHING, related_name='sujets')
    intitule = models.TextField(max_length=255)
    laboratoire = models.ForeignKey(Laboratoire, on_delete=models.DO_NOTHING, related_name='sujets')
    directeur = models.ForeignKey(Enseignant, on_delete=models.DO_NOTHING, related_name='sujets')
    co_directeur = models.ForeignKey(Enseignant, on_delete=models.DO_NOTHING, related_name='co_sujets', null=True, blank=True)

    def __str__(self):
        return f"{self.intitule}"

    @property
    def is_available(self):
        return self.directeur.current_doctorants.count() < 12

class TypeFormationComplementaire(TimeStampedModel):
    class Meta:
        db_table = 'ced_types_formations_complementaires'

    intitule = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.intitule

class FormationComplementaire(TimeStampedModel):
    class Meta:
        db_table = 'ced_formations_complementaires'

    type = models.ForeignKey(TypeFormationComplementaire, on_delete=models.DO_NOTHING, related_name='formations_complementaires')
    formation_doctorale = models.ForeignKey(FormationDoctorale, on_delete=models.DO_NOTHING, related_name='formations_complementaires')
    intitule = models.CharField(max_length=255)
    volume_horaire = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(200)])

    def __str__(self) -> str:
        return self.intitule
        
class LocalisationSoutenance(TimeStampedModel):
    class Meta:
        db_table = 'ced_localisations_soutenance'

    intitule = models.CharField(max_length=255)
    etablissement = models.ForeignKey(Etablissement, on_delete=models.DO_NOTHING)

    def __str__(self) -> str:
        return f"{self.intitule}, {self.etablissement}"

Etudiant/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.core.validators import MaxValueValidator, MinValueValidator
from datetime import datetime
from numpy import busday_count

from CED_Tools.tools.Classes import TimeStampedModel
from CED_Tools.tools.Constants import SEXES, HANDICAPE_CHOICES, SITUATIONS_FAMILIALES
from CED_Tools.tools.Functions import photo_upload_to, cv_upload_to, cursus_document_upload_to, safe_image_tag, birhdayValidator, avg_to_mention, current_year
from CED_Tools.models import Annee, Pays

from Administration.models import Sujet, FormationComplementaire, Enseignant, LocalisationSoutenance

# Create your models here.

class Doctorant(TimeStampedModel):

    class Meta:
        db_table = 'ced_doctorants'
    
    photo = models.ImageField(upload_to=photo_upload_to, max_length=255, blank=True, null=True)
    nom = models.CharField(max_length=63)
    prenom = models.CharField(max_length=63)
    sexe = models.CharField(max_length=1, choices=SEXES)
    cne = models.CharField('CNE', max_length=15)
    cin = models.CharField('CIN', max_length=15, unique=True)
    date_naissance = models.CharField('Date de naissance', max_length=10, validators=(birhdayValidator,), blank=True, null=True)
    lieu_naissance = models.CharField('Lieu de naissance', max_length=255, blank=True, null=True)
    pays = models.ForeignKey(Pays, on_delete=models.DO_NOTHING, default=Pays.default_value_id, related_name='doctorants', blank=True, null=True)
    
    nom_ar = models.CharField(max_length=127, blank=True, null=True)
    prenom_ar = models.CharField(max_length=127, blank=True, null=True)
    lieu_naissance_ar = models.CharField(max_length=255, blank=True, null=True)
    
    adresse = models.CharField(max_length=255, blank=True, null=True)
    ville = models.CharField(max_length=127, blank=True, null=True)

    telephone = PhoneNumberField(blank=True, null=True)
    email_ac = models.EmailField(verbose_name='Email Académique', blank=True, null=True)
    email_pr = models.EmailField(verbose_name='Email Personnelle', blank=True, null=True)

    cv = models.FileField(verbose_name='Curriculum Vitae', upload_to=cv_upload_to, max_length=255, blank=True, null=True)

    handicap = models.CharField(max_length=31, blank=True, null=True, choices=HANDICAPE_CHOICES)
    situation_f = models.CharField(verbose_name='Situation familiale', max_length=1, blank=True, null=True, choices=SITUATIONS_FAMILIALES)

    fonctionnaire = models.BooleanField(default=False, blank=True)
    employeur = models.CharField(max_length=255, blank=True, null=True)
    profession = models.CharField(max_length=255, blank=True, null=True)

    @property
    def email(self):
        return self.email_ac if self.email_ac else self.email_pr

    @property
    def photo_preview(self):
        return safe_image_tag(self.photo.url if self.photo else None)

    def __str__(self) -> str:
        return f"{self.cin.upper()} - {self.nom.upper()} {self.prenom.upper()}"

    @property
    def soutenance(self):
        try:
            return self.soutenances.first()
        except:
            return None

    @property
    def last_inscription(self):
        return self.inscriptions.order_by('-created_at').last()

    @property
    def first_inscription(self):
        return self.inscriptions.order_by('-created_at').first()

class CursusType(TimeStampedModel):
    class Meta:
        db_table = 'ced_cursus_types'
        verbose_name_plural = 'Types de Cursus'

    intitule = models.CharField(max_length=255)
    acronyme = models.CharField(max_length=63)
    description = models.CharField(max_length=255)
    duree_annees = models.IntegerField(validators=[MinValueValidator(1)])

    def __str__(self) -> str:
        return f"{self.intitule} ({self.acronyme})"

    @property
    def duree(self):
        return f"{self.duree_annees} an" + ("s" if self.duree_annees > 1 else "")

class Cursus(TimeStampedModel):
    class Meta:
        db_table = 'ced_cursus'
        verbose_name_plural = 'Cursus'

    doctorant = models.ForeignKey(Doctorant, on_delete=models.DO_NOTHING, related_name='cursus')
    type = models.ForeignKey(CursusType, on_delete=models.DO_NOTHING, related_name='cursus')
    annee = models.ForeignKey(Annee, on_delete=models.DO_NOTHING, related_name='cursus', blank=True, null=True)

    intitule = models.CharField(max_length=255)
    date_obtention = models.DateField("Date d'obtention", blank=True, null=True)
    moyenne = models.DecimalField(decimal_places=2, max_digits=4, validators=[MinValueValidator(10), MaxValueValidator(20)], blank=True, null=True)
    duree = models.IntegerField(verbose_name="Durée (ans)", validators=[MinValueValidator(1)], blank=True, null=True)
    ville = models.CharField(max_length=255, blank=True, null=True)
    etablissement = models.CharField(verbose_name="Etablissement", max_length=255, blank=True, null=True)
    photo_diplome = models.FileField(verbose_name="Diplôme", upload_to=cursus_document_upload_to, max_length=255, blank=True, null=True)
    photo_releve = models.FileField(verbose_name="Relevé des notes", upload_to=cursus_document_upload_to, max_length=255, blank=True, null=True)
    

    @property
    def mention(self):
        return avg_to_mention(self.moyenne)

    @property
    def get_duree(self):
        return f"{self.duree} an" + ("s" if self.duree > 1 else "")

    def __str__(self) -> str:
        return f"{self.type} - {self.intitule}"

class RetraitType(TimeStampedModel):
    class Meta:
        db_table = 'ced_retraits_types'
        verbose_name_plural = 'Types de documents à retirer'
    
    intitule = models.CharField(max_length=255)
    max_delais = models.IntegerField("Délais Maximum", default=3)

    def __str__(self):
        return self.intitule
        
class Retrait(TimeStampedModel):
    class Meta:
        db_table = 'ced_retraits'
        verbose_name_plural = 'Retraits'
    
    type = models.ForeignKey(RetraitType, on_delete=models.DO_NOTHING, related_name='retraits')
    doctorant = models.ForeignKey(Doctorant, on_delete=models.DO_NOTHING, related_name='retraits')
    created_at = models.DateTimeField('date création', auto_now_add=True)
    date_retour = models.DateTimeField(blank=True, null=True)
    definitif = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.type} par {self.doctorant}"

    @property
    def delay(self):
        return busday_count(self.created_at.date(), datetime.now().date()) - self.type.max_delais - 1

    @property
    def is_late(self):
        return self.delay > 0

    def return_date(self):
        if self.definitif:
            return 'Retrait définitif'
        elif self.date_retour:
            return self.date_retour
        elif self.is_late:
            return f"En retard par : {self.delay} {'jours' if self.delay > 1 else 'jour'}"
        else:
            return "--"
     
class Inscription(TimeStampedModel):
    class Meta:
        db_table = 'ced_inscriptions'

    doctorant = models.ForeignKey(Doctorant, on_delete=models.DO_NOTHING, related_name='inscriptions')
    annee = models.ForeignKey(Annee, on_delete=models.DO_NOTHING, related_name='inscriptions', default=current_year)
    sujet = models.ForeignKey(Sujet, on_delete=models.DO_NOTHING, related_name='inscriptions')
    sujet_detail = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return f"({self.annee}) {self.sujet} -- {self.doctorant}"

    @property
    def date(self):
        return self.created_at.strftime("%d/%m/%Y")

class Formation_C_Inscription(TimeStampedModel):
    class Meta:
        db_table = 'ced_fc_inscription'

    inscription = models.ForeignKey(Inscription, on_delete=models.DO_NOTHING, related_name='fomations_complementaires')
    formation_complementaire = models.ForeignKey(FormationComplementaire, on_delete=models.DO_NOTHING, related_name='inscriptions')
    date = models.DateField(blank=True, null=True)

class Publication(TimeStampedModel):
    class Meta:
        db_table = 'ced_publications'
    
    inscription =  models.ForeignKey(Inscription, on_delete=models.DO_NOTHING, related_name='publications')
    intitule = models.CharField(max_length=255)
    description = models.CharField(max_length=255,blank=True, null=True)
    url = models.CharField(max_length=255,blank=True, null=True)
    date = models.DateField(blank=True, null=True)

    @property
    def sujet(self):
        return self.intitule

class Soutenance(TimeStampedModel):
    class Meta:
        db_table = 'ced_soutenances'

    doctorant = models.ForeignKey(Doctorant, on_delete=models.DO_NOTHING, related_name='soutenances')
    speciality = models.CharField('spécialité', max_length=255, blank=True, null=True)
    date = models.DateTimeField(blank=True, null=True)
    localisation = models.ForeignKey(LocalisationSoutenance, on_delete=models.DO_NOTHING, related_name='soutenances', blank=True, null=True)
    president = models.ForeignKey(Enseignant, on_delete=models.DO_NOTHING, related_name='soutenances')
    enseignants = models.ManyToManyField(Enseignant, through='SoutenanceMembers')

    @property
    def rapporteurs(self):
        return self.enseignants.through.objects.filter(rapporteur=True)

    @property
    def members(self):
        return self.enseignants.through.objects.filter(rapporteur=False)

    @property
    def doctorant_email(self):
        return self.emails.filter(address=self.doctorant.email).first()

    @property
    def president_email(self):
        return self.emails.filter(address=self.president.email).first()
    
    @property
    def directeur_email(self):
        return self.emails.filter(address=self.doctorant.last_inscription.sujet.directeur.email).first()

    @property
    def co_directeur_email(self):
        return self.emails.filter(address=self.doctorant.last_inscription.sujet.co_directeur.email).first()

class SoutenanceMembers(TimeStampedModel):

Dashboard/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap5 %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

<html lang="{{ LANGUAGE_CODE|default:'en_us' }}">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/svg" href="{% static '/CED/img/favicon.svg' %}">
    <title>{% block title %}CED{% endblock %}</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static '/CED/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/CED/css/styles.css' %}">

    <!-- Bootstrap JavaScript not in body -->
    {% if 'javascript_in_head'|bootstrap_setting %}
        {% bootstrap_javascript %}
    {% endif %}

    <!-- Jquery -->
    <script src="{% static '/CED/js/jquery-3.6.0.min.js' %}"></script>

    <!-- SweetAlert2 -->
    <script src="{% static '/CED/js/sweetalert2.all.min.js' %}"></script>

    <!-- Cookie library -->
    <script src="{% static '/CED/js/js.cookie.min.js' %}"></script>

    <!-- Axios library -->
    <script src="{% static '/CED/js/axios.min.js' %}"></script>

    <!-- Chart library -->
    <script src="{% static '/CED/js/chart.min.js' %}"></script>

    <!-- Custom JavaScript -->
    <script defer src="{% static '/CED/js/scripts.js' %}"></script>


    <!-- Fontawsome -->
    <script src="{% static '/fontawesome_free/js/all.min.js' %}"></script>
    <link href="{% static '/fontawesome_free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    
    {% block head %}{% endblock %}
</head>
<body>
    <header class="navbar navbar-expand-md navbar-dark bg-dark shadow-sm sticky-top">
        <nav class="container-fluid">
            <a class="navbar-brand" href="{% url 'welcome' %}">
                CED
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav ms-5 me-auto">
                    {% url 'dashboard' as dashboard %}
                    {% if dashboard and perms.Dashboard.view_dashboard %}
                    <li class="nav-item me-3">
                    <a href="{% url 'dashboard' %}" class="nav-link text-light {% if 'dashboard' in request.resolver_match.url_name %}active{% endif %}">
                        <i class="fas fa-chart-bar mr-2"></i>
                        <span class="ms-2">Statistiques</span>
                    </a>
                    </li>
                    {% endif %}

                    {% url 'departement-list' as departement_list %}
                    {% if departement_list and perms.Administration.view_departement %}
                    <li class="nav-item me-3">
                    <a href="{% url 'departement-list' %}" class="nav-link text-light {% if 'departement' in request.resolver_match.url_name %}active{% endif %}">
                        <i class="fas fa-building mr-2"></i>
                        <span class="ms-2">Départements</span>
                    </a>
                    </li>
                    {% endif %}

                    {% url 'enseignant-list' as enseignant_list %}
                    {% if enseignant_list and perms.Administration.view_enseignant %}
                    <li class="nav-item me-3">
                    <a href="{% url 'enseignant-list' %}" class="nav-link text-light {% if 'enseignant' in request.resolver_match.url_name %}active{% endif %}">
                        <i class="fas fa-user-tie mr-2"></i>
                        <span class="ms-2">Enseignants</span>
                    </a>
                    </li>
                    {% endif %}

                    {% url 'doctorant-list' as doctorant_list %}
                    {% if doctorant_list and perms.Etudiant.view_doctorant %}
                    <li class="nav-item me-3">
                    <a href="{% url 'doctorant-list' %}" class="nav-link text-light {% if 'doctorant' in request.resolver_match.url_name %}active{% endif %}">
                        <i class="fas fa-user-graduate mr-2"></i>
                        <span class="ms-2">Doctorants</span>
                    </a>
                    </li>
                    {% endif %}

                    {% url 'formation-list' as formation_list %}
                    {% if formation_list and perms.Administration.view_formation %}
                    <li class="nav-item me-3">
                    <a href="{% url 'formation-list' %}" class="nav-link text-light {% if 'formation' in request.resolver_match.url_name %}active{% endif %}">
                        <i class="fas fa-chalkboard"></i>
                        <span class="ms-2">Formations</span>
                    </a>
                    </li>
                    {% endif %}

                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ms-3">
                    <!-- Authentication Links -->
                    {% if user.is_authenticated %}
                        {% if user.is_staff %}
                        <li class="nav-item">
                            <a class="nav-link font-weight-bold" href="{% url 'admin:index' %}">Admin</a>
                        </li>
                        {% endif %}
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                {{ user }}
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'logout' %}" onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                                    Se déconnecter
                                </a>

                                <form id="logout-form" action="{% url 'logout' %}" method="POST" class="d-none">
                                    {% csrf_token  %}
                                </form>
                            </div>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link font-weight-bold" href="{% url 'login' %}">Se connecter</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <main class="container-fluid d-flex px-0">
    {% block main %}
    {% endblock %}
    </main>
    <footer>
        <div class="container d-flex flex-column flex-md-row justify-content-between py-2 px-4">
            <span class="text-center text-md-start">Faculté des Science Dhar El Mahraz - Fès</span>
            <strong class="text-center">
                <a class="text-white" href="http://fsdmfes.ac.ma">FSDM</a>
                <span>© {% now "Y" %}</span>
            </strong>
            <span class="text-center text-md-end">كـلية العلوم ظهر المهراز - فـــاس</span>
        </div>
    </footer>

    <!-- Bootstrap JavaScript if it is in body -->
    {% if not 'javascript_in_head'|bootstrap_setting %}
        {% bootstrap_javascript %}
    {% endif %}

    {% block scripts %}{% endblock %}
</body>
</html>

Dashboard/templates/welcome.html
{% extends "base.html" %}
{% block head %}<style>main{padding-bottom:0 !important}</style>{% endblock %}
{% block main %}
<div class="welcome-cover">
    <h1 class="text-white">Centre d’Etudes Doctorales en Sciences et Technologies</h1>
</div>
{% endblock %}